### ISSUE TITLE
Is there a reason why props are sometimes destructured but sometimes not?

### ISSUE THREAD

**Issue by gaolbreaker** [Team-Rhydon/Rhydon#42]
https://github.com/Team-Rhydon/Rhydon/blob/40d04d54e9c2931513221959e604c696e21308f0/client/src/Ratings/RatingsWidget.jsx#L9

**Comment by crypto-bender** [comment]
@gaolbreaker Comfort level and timeline.  This was the first component I wrote and destructuring all props seemed like a luxury refactor.

**Comment by gaolbreaker** [comment]
Got it; that makes sense.
