### ISSUE TITLE
let vs const

### ISSUE THREAD

**Issue by gaolbreaker** [Team-Rhydon/Rhydon#43]
https://github.com/Team-Rhydon/Rhydon/blob/40d04d54e9c2931513221959e604c696e21308f0/client/src/Ratings/SortDrop.jsx#L14

If you're not going to reassign the variable, it's safe to just use const when assigning a fat arrow function expression.

**Comment by crypto-bender** [comment]
> https://github.com/Team-Rhydon/Rhydon/blob/40d04d54e9c2931513221959e604c696e21308f0/client/src/Ratings/SortDrop.jsx#L14
> 
> If you're not going to reassign the variable, it's safe to just use const when assigning a fat arrow function expression.

@gaolbreaker Is this just best practices or does it have any optimization effects?

**Comment by gaolbreaker** [comment]
@crypto-bender It's just best practice so it's not a super big deal.
